# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        font = QtGui.QFont()
        font.setPointSize(20)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 241, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 290, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 540, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textPlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.textPlainText.setGeometry(QtCore.QRect(160, 70, 421, 64))
        self.textPlainText.setObjectName("textPlainText")
        self.textKey = QtWidgets.QTextEdit(self.centralwidget)
        self.textKey.setGeometry(QtCore.QRect(160, 180, 421, 64))
        self.textKey.setObjectName("textKey")
        self.textCipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.textCipherText.setGeometry(QtCore.QRect(160, 290, 421, 64))
        self.textCipherText.setObjectName("textCipherText")
        self.textMatrix = QtWidgets.QTextEdit(self.centralwidget)
        self.textMatrix.setGeometry(QtCore.QRect(160, 540, 421, 64))
        self.textMatrix.setReadOnly(True)
        self.textMatrix.setObjectName("textMatrix")
        self.pushEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.pushEncrypt.setGeometry(QtCore.QRect(50, 420, 111, 41))
        self.pushEncrypt.setObjectName("pushEncrypt")
        self.pushDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.pushDecrypt.setGeometry(QtCore.QRect(200, 420, 111, 41))
        self.pushDecrypt.setObjectName("pushDecrypt")
        self.pushCreateMatrix = QtWidgets.QPushButton(self.centralwidget)
        self.pushCreateMatrix.setGeometry(QtCore.QRect(350, 420, 181, 41))
        self.pushCreateMatrix.setObjectName("pushCreateMatrix")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PLAYFAIR CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain Text:"))
        self.label_3.setText(_translate("MainWindow", "Key:"))
        self.label_4.setText(_translate("MainWindow", "Cipher Text:"))
        self.label_5.setText(_translate("MainWindow", "Matrix:"))
        self.pushEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.pushDecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.pushCreateMatrix.setText(_translate("MainWindow", "Create Matrix"))
